"""Read-only Research Workbench projections over the platform registry."""

from app.research_workbench.builder import (
    COMMAND_PROFILE,
    COMMAND_VERSION,
    MANIFEST_VERSION,
    build_research_workbench_backend,
    finalize_research_workbench_backend,
    verify_research_workbench_inputs,
)
from app.research_workbench.errors import (
    ArtifactNotFound,
    EvidenceNotFound,
    InvalidWorkbenchQuery,
    LineageNodeNotFound,
    ResearchFamilyNotFound,
    StrategyNotFound,
    WorkbenchIntegrityError,
)
from app.research_workbench.models import (
    BlockedResearchSummary,
    EvidenceSummary,
    FamilySortField,
    ResearchArtifactSummary,
    ResearchConclusion,
    ResearchConclusionClassification,
    ResearchEvidenceDetail,
    ResearchFamilyDetail,
    ResearchFamilyPage,
    ResearchFamilyQuery,
    ResearchFamilySummary,
    ResearchLineageSummary,
    ResearchLineageTrace,
    ResearchProgrammeSummary,
    ResearchStrategyDetail,
    ResearchTimelineEvent,
    ResearchWorkbenchIntegritySummary,
    ResearchWorkbenchSnapshot,
    ValidationSummary,
)
from app.research_workbench.service import ResearchWorkbenchService

__all__ = (
    "ArtifactNotFound",
    "BlockedResearchSummary",
    "COMMAND_PROFILE",
    "COMMAND_VERSION",
    "EvidenceNotFound",
    "EvidenceSummary",
    "FamilySortField",
    "InvalidWorkbenchQuery",
    "LineageNodeNotFound",
    "MANIFEST_VERSION",
    "ResearchArtifactSummary",
    "ResearchConclusion",
    "ResearchConclusionClassification",
    "ResearchEvidenceDetail",
    "ResearchFamilyDetail",
    "ResearchFamilyNotFound",
    "ResearchFamilyPage",
    "ResearchFamilyQuery",
    "ResearchFamilySummary",
    "ResearchLineageSummary",
    "ResearchLineageTrace",
    "ResearchProgrammeSummary",
    "ResearchStrategyDetail",
    "ResearchTimelineEvent",
    "ResearchWorkbenchIntegritySummary",
    "ResearchWorkbenchService",
    "ResearchWorkbenchSnapshot",
    "StrategyNotFound",
    "ValidationSummary",
    "WorkbenchIntegrityError",
    "build_research_workbench_backend",
    "finalize_research_workbench_backend",
    "verify_research_workbench_inputs",
)
