"""Provider-neutral InterSignal platform registry foundation."""

from app.platform.hashing import (
    HASH_VERSION,
    canonical_hash,
    canonical_json,
    deterministic_id,
    file_sha256,
)
from app.platform.models import (
    ArtifactImmutabilityStatus,
    ArtifactRecord,
    ArtifactType,
    EvidenceClassification,
    EvidenceLevel,
    EvidenceRecord,
    EvidenceStatus,
    LineageEdge,
    LineageNode,
    LineageRelationship,
    LineageStage,
    ProvenanceRecord,
    RegistryEntityType,
    RegistryEvent,
    RegistryEventType,
    StrategyLifecycle,
    StrategyRecord,
    build_artifact_record,
    build_lineage_edge,
    build_lineage_node,
)
from app.platform.policies import InvalidLifecycleTransition, validate_transition
from app.platform.repositories import (
    ArtifactRegistryRepository,
    DuplicateIdentityError,
    EvidenceRegistryRepository,
    InMemoryPlatformRepository,
    JsonFilePlatformRepository,
    LineageCycleError,
    LineageRepository,
    MissingReferenceError,
    RegistryEventRepository,
    StrategyRegistryRepository,
)
from app.platform.services import PlatformRegistryService

__all__ = (
    "ArtifactImmutabilityStatus",
    "ArtifactRecord",
    "ArtifactRegistryRepository",
    "ArtifactType",
    "DuplicateIdentityError",
    "EvidenceClassification",
    "EvidenceLevel",
    "EvidenceRecord",
    "EvidenceRegistryRepository",
    "EvidenceStatus",
    "HASH_VERSION",
    "InMemoryPlatformRepository",
    "InvalidLifecycleTransition",
    "JsonFilePlatformRepository",
    "LineageCycleError",
    "LineageEdge",
    "LineageNode",
    "LineageRelationship",
    "LineageRepository",
    "LineageStage",
    "MissingReferenceError",
    "PlatformRegistryService",
    "ProvenanceRecord",
    "RegistryEntityType",
    "RegistryEvent",
    "RegistryEventRepository",
    "RegistryEventType",
    "StrategyLifecycle",
    "StrategyRecord",
    "StrategyRegistryRepository",
    "build_artifact_record",
    "build_lineage_edge",
    "build_lineage_node",
    "canonical_hash",
    "canonical_json",
    "deterministic_id",
    "file_sha256",
    "validate_transition",
)
